tasty_food/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('web/', include('web.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Tasty Food / T-mob"
admin.site.site_title = "Tasty Food Admin"
admin.site.index_title = "Welcome to Tasty Food"

tasty_food/apps/categories/models.py
# coding: utf-8

from django.db import models
from django.utils.translation import ugettext as _
from .validate import validate_svg

class Category(models.Model):

    class Meta:
        verbose_name_plural = ('Categories')
        db_table = 'tasty_food_categories'

    name = models.CharField(_('name'), max_length=50)
    icon = models.FileField(_('icon'), upload_to='icons', validators=[validate_svg], help_text="Icono de la categoria mostrado en el listado de las mismas.")
    banner = models.FileField(_('banner'), upload_to='banners', validators=[validate_svg], help_text="Banner de la categoria mostrado en la descripcion de la misma.")
    active = models.BooleanField(_('active'), default=True)

    def __str__ (self):
        return self.name

tasty_food/apps/recipes/models.py
# coding: utf-8

from django.db import models
from django.utils.translation import ugettext as _
from django import forms
from categories.models import Category
from chefs.models import Chef


class Recipe(models.Model):

    class Meta:
        verbose_name = ('recipe')
        verbose_name_plural = ('recipes')
        db_table = 'tasty_food_recipes'

    CHOICE_TIME_DURATION = (('5', '5 Minutos'), 
                            ('10', '10 Minutos'),
                            ('15', '15 Minutos'),
                            ('20', '20 Minutos'),
                            ('25', '25 Minutos'),
                            ('30', '30 Minutos'),
                            ('35', '35 Minutos'),
                            ('40', '40 Minutos'),
                            ('45', '45 Minutos'),
                            ('50', '50 Minutos'),
                            ('55', '55 Minutos'),
                            ('60', '1hr'),
                            ('65', '1hr 5 Minutos'),
                            ('70', '1hr 10 Minutos'),
                            ('75', '1hr 15 Minutos'),
                            ('80', '1hr 20 Minutos'),
                            ('90', '1hr 30Minutos'),
                            )
    CHOICE_LEVEL = (('1', 'Facil'),
                    ('2', 'Medio'),
                    ('3', 'Dificil'),
                    )
    
    name = models.CharField(_("name"), max_length=50)
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active = models.BooleanField("active", default=True)

    video = models.URLField(_("video URL"),max_length=200, null=True, blank=True)
    spotify = models.URLField(_("spotify URL"),max_length=200, null=True, blank=True)
    #image = models.ImageField()

    duration = models.CharField(_("duration"), choices=CHOICE_TIME_DURATION, max_length=5)
    level = models.CharField(_("level"),choices=CHOICE_LEVEL, max_length=15)
    serving = models.IntegerField(_("serving"), )

    updated_at = models.DateTimeField(auto_now=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__ (self):
        return self.name
    
    def preview(self):
        #if self.video:
        #    return self.video
        return self.images.all().order_by('order')[0].image.url

class Ingredient(models.Model):

    class Meta:
        verbose_name = _('ingredient')
        verbose_name_plural = _('ingredients')
        db_table = 'tasty_food_ingredients'

    name = models.CharField(max_length=50)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

    def __str__ (self):
        return self.name


class Step(models.Model):

    class Meta:
        verbose_name = _('step')
        verbose_name_plural = _('steps')
        db_table = 'tasty_food_steps'

    order = models.PositiveSmallIntegerField()
    process = models.TextField("Proceso")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='steps')

    def __str__ (self):
        return self.process

class ImageRecipe(models.Model):

    class Meta:
        verbose_name = _('image recipe')
        verbose_name_plural = _('images recipe')
        db_table = 'tasty_food_images_recipe'

    order = models.PositiveSmallIntegerField()
    image = models.ImageField(upload_to='recipe')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='images')

tasty_food/apps/users/models.py
from django.db import models
from recipes.models import Recipe

class User(models.Model):
    number = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    service_id = models.IntegerField(blank=False)

    def __str__ (self):
        return self.number

class Favorites(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fav_recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__ (self):
        return self.user

tasty_food/apps/categories/controller.py
from .models import Category
from django.core.cache import cache
from django.conf import settings
from settings.local import CACHE_CATEGORY

def reload_cache_category():

    categories = Category.objects.filter(active=True)
    cat_cache = {category.id:category for category in categories }
    cache.set(settings.CACHE_CATEGORY, cat_cache)
    return cat_cache



def get_category(category_id):
    
    cat_cache = cache.get(settings.CACHE_CATEGORY) 
    if not cat_cache:                               
        cat_cache = reload_cache_category() 

    try:
        category = cat_cache[category_id]
        return category
    except:
        return None



def get_categories():

    cat_cache = cache.get(settings.CACHE_CATEGORY) 
    if not cat_cache:                               
        cat_cache = reload_cache_category()
    
    categories = list(cat_cache.values())
    categories.sort(key=lambda x: x.name)
    return categories

tasty_food/apps/categories/views.py
from django.shortcuts import render

# Create your views here.

tasty_food/apps/recipes/views.py
from django.shortcuts import render

# Create your views here.

tasty_food/apps/users/views.py
from django.shortcuts import render

# Create your views here.

tasty_food/apps/web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <!---Font Icon-->
    <link href="{% static "web/css/font-awesome.min.css" %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

     <meta name="apple-mobile-web-app-capable" content="yes" />
     <meta name="mobile-web-app-capable" content="yes">
     <meta name="description" content="Tasty Food">
     <meta name="author" content="T-mob">
     <link rel="apple-touch-icon-precomposed" href="{% static "web/images/apple-touch-icon-precomposed.png" %}" >
     <link rel="apple-touch-icon-precomposed" href="{% static "web/images/apple-touch-icon-72x72-precomposed.png" %}" >
     <link rel="apple-touch-icon-precomposed" href="{% static "web/images/apple-touch-icon-114x114-precomposed.png" %}" >
     <link rel="apple-touch-icon-precomposed" href="{% static "web/images/apple-touch-icon-144x144-precomposed.png" %}" >


    <!-- CSS -->
    <link href="{% static "web/css/bootstrap.min.css" %}"  rel="stylesheet">
    <link href="{% static "web/css/loadbuttons.css" %}" rel="stylesheet">
    <link href="{% static "web/css/styles.min.css" %}"  rel="stylesheet">
    <link href="{% static "web/css/select2.min.css" %}"  rel="stylesheet">
	<link href="{% static "web/css/style.css" %}"  rel="stylesheet">
	<link href="{% static "web/css/slick.css" %}"  rel="stylesheet">
	<link href="{% static "web/css/slick-theme.css" %}"  rel="stylesheet">
	<link href="{% static "web/css/coolshare.css" %}"  rel="stylesheet">
	<link href="{% static "web/css/fancy-checkbox.css" %}" rel="stylesheet">
	<link href="{% static "web/css/step-list.css" %}" rel="stylesheet">

    <script src="{% static "web/js/modernizr.custom.js" %}" ></script>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static "web/images/favicon.png" %}"  />
    <link rel="icon" href="{% static "web/images/favicon.png" %}"  />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

    <!--[if lt IE 9]>

    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

</head>
<body>
	 <!-- MENU -->

   <nav class="navbar navbar-light fixed-top">
       <div class="container-fluid justify-content-center">
     <a href="index.html"><h5 class="orange mb-0">{{title}}</h5></a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><span class=""><i class="fa fa-search"></i></span>
     </button>

           <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">

               <!-- Search -->

   <div class="search pb-0">
       <div class="container">
           <div class="row">
               <div class="col-lg-12">
                   <form action="{% url 'search' %}" method="post">
                       {% csrf_token %}
                   <div class="row">
                       <div class="col-lg-12 col-md-12 col-sm-12">
                           <div class="form-group">
                               <label>Seleccioná Categoría</label>
                               <select class="js-search-category form-control" name="category" data-placeholder="Choose Category">
                                   {% for category in categories %}
                                       <option value="{{category.id}}">{{category.name}}</option>
                                   {% endfor %}
                               </select>
                           </div>
                       </div>
                       <div class="col-lg-12">
                           <div class="form-group text-center">
                               <input type="text" class="form-control" placeholder="Buscar por ingrediente" name="ingredient">
                               <button type="submit" class="btn btn-primary btn-search">Buscar</button>
                           </div>
                       </div>
                   </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
           </div>
       </div>
   </nav>

	{% block content %}

    {% endblock %}

    <!-- Navigation -->

    <div id="navigation">
  <nav class="navbar-bottom navbar-expand">
    <ul class="navbar-nav">
      <li class="nav-item"><a href="{% url 'home' %}" class="nav-link {% if page == 'home' %} active {% endif %}"><i class="fas fa-home"></i></a></li>
      <li class="nav-item"><a href="{% url 'categories' %}" class="nav-link {% if page == 'categories' %} active {% endif %}"><i class="fas fa-utensils"></i></a></li>
      <li class="nav-item"><a href="{% url 'favorites' %}" class="nav-link {% if page == 'favorites' %} active {% endif %}"><i class="fas fa-heart"></i></a></li>
	<li class="nav-item"><a href="{% url 'videos' %}" class="nav-link {% if page == 'videos' %} active {% endif %}"><i class="fas fa-video"></i></a></li>
    </ul>
  </nav>

</div>



    <!-- Javascript -->

    <script src="{% static "web/js/jquery.min.js"%}"></script>
    <script src="{% static "web/js/popper.min.js"%}"></script>
    <script src="{% static "web/js/bootstrap.min.js"%}"></script>
    <script src="{% static "web/js/select2.min.js"%}"></script>
    <script src="{% static "web/js/jquery-ui.js"%}"></script>
	<script src="{% static "web/js/slick.min.js"%}"></script>
	<script src="{% static "web/js/slick-responsive.js"%}"></script>
    <script src="{% static "web/js/scripts.js"%}"></script>
	<script src="{% static "web/js/coolshare.js"%}"></script>
	<script src="{% static "web/js/fancy-checks.js"%}"></script>




</body>



</html>

tasty_food/apps/web/templates/web/categories.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}
{% if categories %}
<div class="featured">
    <div class="container">
        <div class="row justify-content-center">
            <!-- Categories-->
            <div class="col-lg-8 col-md-12 col-sm-12">
                {% for category in categories %}
                <div class="category-box">
                    <span class="food-icon">
                        <img src="{{category.icon.url}}"> 
                    </span>
                    <a href="{% url 'category' category.id %}">{{category.name}}</a>
                </div>
                {% endfor%}

                <div class="category-box">
                    <span class="food-icon">
                        <img src="{% static "web/images/icon_chef.svg" %}"> 
                    </span>
                    <a href="{% url 'chefs' %}">CHEFS</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="featured">
    <div class="container">
        <div class="row justify-content-center">
            <!-- No Categories-->
            <div class="col-lg-8 col-md-12 col-sm-12">
                <div class="empty-container mt-4 mb-5">
                    <img src="{% static "web/images/empty-categories.svg" %}">
                </div>
                <div class="form-group">
                    <h5 class="mt-3 mb-3">No se encontraron Categorías</h5>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

tasty_food/apps/web/templates/web/category.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

	<!-- Image Recipes-->

    <div class="featured recipe-page">
		<div class="row">
			<div class="col-12 image-recipe">
			<img src="{{category.banner.url}}">
			</div>
		</div>

        <div class="container mt-4">

            <div class="row justify-content-center">

                <div class="col-lg-12 mb-4">
                    <p class="category">CATEGORÍA</p>
					<h3 class="mb-3"><a href="recipe-detail.html">{{category.name}}</a></h3>
					<div class="tag">
							<span>{{total_recipes}} Recetas</span>
                        </div>
                </div>        

               <div class="col-lg-8 col-md-12 col-sm-12">
               
                {% for recipe in recipes %}
                    <div class="box grid recipes">
                        <a href="{% url 'recipe' recipe.id %}"><img src="{{recipe.preview}}" alt=""></a>
                        <h3 class="mb-3 text-left"><a href="recipe-detail.html">{{recipe.name}}</a></h3>
                        <div class="tag">
							<span class="float-left mt-tag"><i class="fa fa-clock mr-1"></i>{{recipe.get_duration_display}}</span>
							<span class=""><i class="fas fa-sliders-h mr-1"></i>{{recipe.get_level_display}}</span>
							<span class="float-right mt-tag"><i class="fas fa-utensils mr-1"></i>{{recipe.serving}}Comensal{{ recipe.serving|pluralize:"es" }}</span>
                        </div>
                    </div>

                {% endfor %}
                
                </div>
				</div>

			<div class="col-lg-12">
            </div>
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/chef_detail.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

	<!-- Image Recipes-->

    <div class="featured recipe-page">
		<div class="row">
			<div class="col-12 image-recipe">
			<img src="{{chef.image.url}}">
			</div>
		</div>

        <div class="container mt-4">

            <div class="row justify-content-center">

                <div class="col-lg-12 mb-4">
					<h3 class="mb-1">{{chef.name}}</h3>
          <div class="tag mb-3">
              <span><i class="fa fa-book-open mr-1"></i>{{n_recipes}} Recetas</span>
          </div>
          <div class="row list-box justify-content-center bg-white">
  				<div class="col-12">
          <p class="chef-bio">
           <strong>Biografía</strong><br /></p>
          <p class="chef-bio">{{chef.biography}}</p>
          </div>
  			  </div>
        </div>
			 	<div class="col-lg-8 col-md-12 col-sm-12">
                {% for recipe in recipes %}
                    <div class="box grid recipes">
                        <a href="{% url 'recipe' recipe.id %}"><img src="{{recipe.preview}}" alt=""></a>
                        <h3 class="mb-3 text-left"><a href="recipe-detail.html">{{recipe.name}}</a></h3>
                        <div class="tag">
							<span class="float-left mt-tag"><i class="fa fa-clock mr-1"></i>{{recipe.get_duration_display}}</span>
							<span class=""><i class="fas fa-sliders-h mr-1"></i>{{recipe.get_level_display}}</span>
							<span class="float-right mt-tag"><i class="fas fa-utensils mr-1"></i>{{recipe.serving}} Comensal{{ recipe.serving|pluralize:"es" }}</span>
                        </div>
                    </div>

                {% endfor %}

                </div>
				</div>

			<div class="col-lg-12">
            </div>
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/chef_list.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}
    <div class="featured recipe-page">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-12 col-sm-12">
                    {% for chef in chefs %}
                        <div class="box grid recipes mt-4">
                            <a href="{% url 'chef' chef.id %}"><img src="{{chef.image.url}}" alt=""></a>
                            <h3 class="mb-0">{{chef.name}}</h3>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-12"> </div>
        </div>
    </div>
{% endblock %}

tasty_food/apps/web/templates/web/index.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

<!-- Featured Recipes-->

    <div class="featured">

        <div class="container">

            <div class="row justify-content-center">

                <div class="col-lg-12">

                    <h5 class="text-left mb-3">{{showcase.0.name}}</h5>

                </div>
                <div class="col-lg-12 pr-0">
                    <div class="featured-recipes home-slide mb-3">
                        {% for recipe_in in showcase.0.recipes.all %}
                        <div><a href="{% url 'recipe' recipe_in.recipe.id%}"><img src="{{ recipe_in.recipe.preview }}"></a></div>
                        {% endfor %}

                        {% for chef_in in showcase.0.chef.all %}
                        <div><a href="{% url 'chef' chef_in.chef.id %}"><img src="{{ chef_in.chef.preview }}"></a></div>
                        {% endfor %}
                    </div>
                </div>

				<!-- Lasts Recipes-->

                <div class="col-lg-12">
                    <h5 class="text-left mb-3">{{showcase.1.name}}</h5>
                </div>

                <div class="col-lg-8 col-md-12 col-sm-12">
                    {% for recipe_in in showcase.1.recipes.all %}
                    <div class="box grid recipes">
                        <a href="{% url 'recipe' recipe_in.recipe.id%}"><img src="{{recipe_in.recipe.preview}}" alt=""></a>
                        <div class="row">
                            <div class="col-8">
                                <p class="category text-left">{{recipe_in.recipe.category.name}}</p>
                            </div>
                            <div class="col-4 mt--7">
                                <ul>
                                    <li class="social-link"><a href="#" onClick="return false;" class=""><i class="fa fa-heart fa-selected"></i></a></li>
                                    <!--<li class="social-link"><a href="#" onClick="return false;" class="socialShare"></a></li>-->
                                </ul>
                            </div>
                        </div>
                        <h3 class="mb-3 text-left"><a href="recipe-detail.html">{{recipe_in.recipe.name}}</a></h3>
                        <div class="tag">
                            <span class="float-left mt-tag"><i class="fa fa-clock mr-1"></i>{{recipe_in.recipe.get_duration_display}}</span>
                            <span class=""><i class="fas fa-sliders-h mr-1"></i>{{recipe_in.recipe.get_level_display}}</span>
                            <span class="float-right mt-tag"><i class="fas fa-utensils mr-1"></i>{{recipe_in.recipe.serving}} Comensal{{ recipe_in.recipe.serving|pluralize:"es" }}</span>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/msisdn.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

    <!-- Login form-->

	<div class="page contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12 title text-center mb-2 mt-4">
					<h1>Registrate</h1>
					<p>¡Y empezá a comer rico!</p>
                </div>
                <div class="col-lg-8 content text-center mt-4">
                    <form>
                        <div class="form-group featured">
                            <input type="text" class="form-control" placeholder="Número de celular">
                            <span>Sin 15 y código de área. Ej: 11XXXXXXXX</span>
                        </div>
                        <a href="pincode.html" class="btn btn-primary mb-4">enviar</a><br/>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/notifications.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

	<!-- Notifications-->

	<div class="top">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="box clearfix">
                        <a href="recipe-detail.html"><img src="{% static "web/images/square-recipes1.jpg" %}" alt=""></a>
                        <h3><a href="recipe-detail.html">Galletas con canela</a></h3>
                        <p>Lorem ipsum dolor sit amet, adipiscing elit...</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box clearfix">
                        <a href="recipe-detail.html"><img src="{% static "web/images/square-recipes2.jpg" %}" alt=""></a>
                        <h3><a href="recipe-detail.html">Mix de frutas con jugo de limón</a></h3>
                        <p>Lorem ipsum dolor sit amet, adipiscing elit...</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="box clearfix read">
                        <a href="recipe-detail.html"><img src="{% static "web/images/square-recipes3.jpg" %}" alt=""></a>
                        <h3><a href="recipe-detail.html">Tarta de queso y frutos rojos</a></h3>
                        <p>Lorem ipsum dolor sit amet, adipiscing elit...</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/pincode.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}

    <!-- Login form-->

	<div class="page contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12 title text-center mb-2 mt-4">
					<h1>Registrate</h1>
					<p>¡Y empezá a comer rico!</p>
                </div>
                <div class="col-lg-8 content text-center mt-4">
                    <form>
                        <div class="form-group featured">
                            <input type="text" class="form-control" placeholder="PIN">
                            <span>Ingresá el PIN recibido</span>
                        </div>
                        <a href="error.html" class="btn btn-primary mb-4">enviar</a><br/>
                    </form>
                </div>
            </div>
        </div>
    </div>

 {% endblock %}

tasty_food/apps/web/templates/web/recipe.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}	
    
    <!-- Image Recipes-->

    <div class="featured recipe-page">
		<div class="row">
			<div class="col-12 image-recipe">
     <div class="recipe-slide">
         {% if recipe.video %}
             <iframe src="{{recipe.video}}" width="320" height="180" frameborder="0" allowfullscreen></iframe>
         {% endif %}
         {% for img in recipe.images.all %}
             <img src="{{img.image.url}}" alt="header">
         {% endfor %}
    </div>
			</div>
		</div>

        <div class="container mt-4">

            <div class="row justify-content-center">

                <div class="col-lg-12">
                    <p class="category">{{recipe.category.name}}</p>
					<h3 class="mb-3"><a href="recipe-detail.html">{{recipe.name}}</a></h3>
					 <div class="tag">

                         
							<span class="float-left mt-tag"><i class="fa fa-clock mr-1"></i>{{recipe.get_duration_display}}</span>
							<span class=""><i class="fas fa-sliders-h mr-1"></i>{{recipe.get_level_display}}</span>
							<span class="float-right mt-tag"><i class="fas fa-utensils mr-1"></i>{{recipe.serving}} Comensal{{ recipe.serving|pluralize:"es" }}</span>
                        </div>
                    {% if recipe.spotify %}
					    <a href="recipe.spotify" class="btn btn-primary listen-link"><i class="fas fa-headphones mr-2"></i>Cociná con esta playlist</a>
                    {% endif %}
                    <h5 class="mt-3 mb-3">Ingredientes</h5>
                </div>
			   </div>
			  <div class="row list-box justify-content-center bg-white">

				<div class="col-12">
                                <ul class="ingredients fancy">
								{% for ingredient in recipe.ingredients.all %}
									<li><span>{{ingredient.name}}<label for=""><input id="" name="" type="checkbox" value=""/></label></span></li>
								{% endfor %}
                                </ul>
                            </div>
			  </div>
			<div class="col-lg-12">
			 <h5 class="mt-4 mb-3">Paso a Paso</h5>
            </div>
			<div class="row bg-white recipe-detail mb-4">
				<div class="col-12">
							   <ol class="directions">
							   {% for step in steps%}
                                    <input class="tgl tgl-flip" id= "cb{{ forloop.counter0 }}" type="checkbox"/>
    								<label class="tgl-btn" data-tg-off="{{step.order}}" for="cb{{ forloop.counter0 }}"></label>
								   	<li>{{step.process}}</li>
								{% endfor %}
                                </ol>
                            </div>
			</div>
			<!--<div class="col-lg-12">
            <span class="social-recipe ml-0">
              <a class="fa fa-twitter" href="https://twitter.com/intent/tweet"></a>
              <a class="fa fa-facebook" href="https://facebook.com/sharer.php"></a>
              <a class="fa fa-google-plus" href="https://plus.google.com/share"></a>
            </span>
          </div>-->
        </div>
    </div>

{% endblock %}

tasty_food/apps/web/templates/web/search-results.html
{% extends 'web/base.html' %}

{% load static %}
{% block content %}
{% if recipes%}
<!-- Featured Recipes-->
<div class="featured">
    <div class="container">
        <div class="row justify-content-center">
            <!-- Results-->
            <div class="col-lg-8 col-md-12 col-sm-12">
                {% for recipe in recipes %}
                <div class="box grid recipes">
                    <a href="{% url 'recipe' recipe.id %}"><img src="{{recipe.preview}}" alt=""></a>
                    <div class="row">
                        <div class="col-8">
                            <p class="category text-left">{{recipe.category.name}}</p>
                        </div>
                        <div class="col-4 mt--7">
                            <ul>
                                <li class="social-link"><a href="#" onClick="return false;" class=""><i class="fa fa-heart fa-selected"></i></a></li>
                                <!--<li class="social-link"><a href="#" onClick="return false;" class="socialShare"></a></li>-->
                            </ul>
                        </div>
                    </div>
                    <h3 class="mb-3 text-left"><a href="recipe-detail.html">{{recipe.name}}</a></h3>
                    <div class="tag">
                        <span class="float-left mt-tag"><i class="fa fa-clock mr-1"></i>{{recipe.get_duration_display}}</span>
                        <span class=""><i class="fas fa-sliders-h mr-1"></i>{{recipe.get_level_display}}</span>
                        <span class="float-right mt-tag"><i class="fas fa-utensils mr-1"></i>{{recipe.serving}} Comensal{{ recipe.serving|pluralize:"es" }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="featured">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-12 col-sm-12">
                <div class="empty-container mt-4 mb-5">
                    <img src="{% static "web/images/empty-recipes.svg" %}">
                </div>
                <div class="form-group">
                    <h5 class="mt-3 mb-3">No se encontraron recetas</h5>
                    <a href="{% url 'home'%}" class="btn btn-secondary">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock%}